#!/bin/bash

set -euo pipefail

export LK_PLATFORM_BRANCH=${LK_PLATFORM_BRANCH:-develop} \
    HOMEBREW_ARTIFACT_DOMAIN=http://brew.mirror

FILE=~/lk-provision-macos.sh
URL=https://raw.githubusercontent.com/lkrms/lk-platform/$LK_PLATFORM_BRANCH/bin/lk-provision-macos.sh

[ -e "$FILE" ] ||
    curl --location --output "$FILE" "$URL" ||
    rm -f "$FILE"

[ -e "$FILE" ] &&
    bash "$FILE" "$@" || exit

. /opt/lk-platform/lib/bash/common.sh
lk_require macos

lk_macos_setenv HOMEBREW_ARTIFACT_DOMAIN http://brew.mirror
