#!/bin/bash

VSCODE_EXTENSIONS=(
    ahmadalli.vscode-nginx-conf
    alefragnani.Bookmarks
    alexcvzz.vscode-sqlite
    beaglefoot.awk-ide-vscode
    bmewburn.vscode-intelephense-client
    chenxsan.vscode-standardjs
    dakara.transformer
    dbaeumer.vscode-eslint
    DotJoshJohnson.xml
    dracula-theme.theme-dracula
    eamodio.gitlens
    felixfbecker.php-debug
    foxundermoon.shell-format
    gharveymn.nightswitch-lite
    giovdk21.vscode-sublime-merge
    henriiik.vscode-sort
    HookyQR.beautify
    humao.rest-client
    idleberg.applescript
    jkjustjoshing.vscode-text-pastry
    jprestidge.theme-material-theme
    jq-syntax-highlighting.jq-syntax-highlighting
    jrebocho.vscode-random
    lkrms.inifmt
    mads-hartmann.bash-ide-vscode
    mgmcdermott.vscode-language-babel
    Mikael.Angular-BeastCode
    mitchdenny.ecdc
    mrmlnc.vscode-apache
    ms-azuretools.vscode-azurefunctions
    ms-azuretools.vscode-azureresourcegroups
    ms-python.python
    ms-python.vscode-pylance
    ms-vscode-remote.remote-ssh-edit
    ms-vscode.azure-account
    ms-vscode.cpptools
    ms-vscode.powershell
    mtxr.sqltools
    piotrpalarz.vscode-gitignore-generator
    PKief.material-icon-theme
    pthorsson.vscode-jsp
    rangav.vscode-thunder-client
    rebornix.ruby
    redhat.java
    redhat.vscode-commons
    redhat.vscode-xml
    redhat.vscode-yaml
    ryu1kn.partial-diff
    salesforce.salesforce-vscode-slds
    salesforce.salesforcedx-vscode
    salesforce.salesforcedx-vscode-apex
    salesforce.salesforcedx-vscode-apex-debugger
    salesforce.salesforcedx-vscode-apex-replay-debugger
    salesforce.salesforcedx-vscode-core
    salesforce.salesforcedx-vscode-lightning
    salesforce.salesforcedx-vscode-lwc
    salesforce.salesforcedx-vscode-soql
    salesforce.salesforcedx-vscode-visualforce
    sfodje.perltidy
    shardulm94.trailing-spaces
    stansw.vscode-odata
    stkb.rewrap
    TaoKlerks.poor-mans-t-sql-formatter-vscode
    teabyii.ayu
    timonwong.shellcheck
    trixnz.vscode-lua
    twxs.cmake
    Tyriar.lorem-ipsum
    Tyriar.sort-lines
    wingrunr21.vscode-ruby
    wmaurer.change-case
    yzhang.markdown-all-in-one
    zhuangtongfa.material-theme
)
